CREATE TABLE MigrationHistory (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    fileNumber INTEGER,
    versionNumber INTEGER,
    dateApplied TIMESTAMP
);

INSERT INTO MigrationHistory (fileNumber,versionNumber,dateApplied) VALUES (0,01,NOW())