CREATE TABLE Tag (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    creator uuid REFERENCES Users (uid),
    name varchar(40) NOT NULL,
    sortOrder integer DEFAULT 0
);

INSERT INTO MigrationHistory (fileNumber,versionNumber,dateApplied) VALUES (02,01,NOW())